### ISSUE TITLE
Windows version and pythonbuddy.com

### ISSUE THREAD

**Issue by x011** [ethanchewy/OnlinePythonLinterSyntaxChecker#4]
The first example on pythonbuddy.com doesn't work.
I couldn't make it work on windows. I get the server running on port 5000, the page is displayed but no input box is available to insert code, here's the log:

 * Serving Flask app "app"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [23/Mar/2017 08:56:41] "GET / HTTP/1.1" 200 -
No config file found, using default configuration
127.0.0.1 - - [23/Mar/2017 08:56:42] "GET /check_code?text=print+%22hello+world%22%0A++++ HTTP/1.1" 200 -
run_test
127.0.0.1 - - [23/Mar/2017 08:56:48] "GET /run_code?text=print+%22hello+world%22%0A++++ HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "e:\Anaconda2\envs\venv\lib\site-packages\werkzeug\serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "e:\Anaconda2\envs\venv\lib\site-packages\werkzeug\serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "e:\Anaconda2\envs\venv\lib\site-packages\flask\app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "e:\Anaconda2\envs\venv\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "e:\Anaconda2\envs\venv\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "e:\Anaconda2\envs\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Anaconda2\envs\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Anaconda2\envs\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\Anaconda2\envs\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Anaconda2\envs\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrador.DESKTOP-K5H10KV\Desktop\python\OnlinePythonLinterSyntaxChecker\app.py", line 74, in run_code
    p = Popen(cmd, shell=True, stdin=PIPE, stdout=PIPE, stderr=STDOUT, close_fds=True)
  File "e:\Anaconda2\envs\venv\lib\subprocess.py", line 347, in __init__
    raise ValueError("close_fds is not supported on Windows "
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

**Comment by ethanchewy** [comment]
It's because you are running this in Windows. I'm not too familiar with anaconda so you'd have to debug more deeply into the issue. It's related to Python.

Also, make sure you are running Python 2.7 in Windows.

Perhaps this will help: https://github.com/gevent/gevent/issues/669
